import type {
  FarmOperation,
  FarmOperationId,
  MachineryProvider,
  MachineType,
} from "./types";

/**
 * Curated machinery service dataset.
 * Deterministic: same operation → same machines, same ordering, every time.
 * Sample data — availability reflects this dataset, not live provider feeds.
 */

export const FARM_OPERATIONS: FarmOperation[] = [
  {
    id: "seedbed-preparation",
    name: "Seedbed preparation",
    description: "Till and level the field so it is ready for sowing.",
    category: "field-preparation",
    suitableMachineTypes: ["tractor", "rotavator"],
    approximateDuration: "Half day for 4–8 acres (estimate)",
  },
  {
    id: "sowing",
    name: "Sowing",
    description: "Find suitable equipment for sowing seed rows.",
    category: "planting",
    suitableMachineTypes: ["seed-drill", "tractor"],
    approximateDuration: "Half day for 6–8 acres (estimate)",
  },
  {
    id: "spraying",
    name: "Spraying",
    description: "Find equipment for crop protection operations.",
    category: "crop-care",
    suitableMachineTypes: ["sprayer"],
    approximateDuration: "1–2 hours for 8–10 acres (estimate)",
  },
  {
    id: "harvesting",
    name: "Harvesting",
    description: "Explore available harvesting equipment for standing crops.",
    category: "harvest-post-harvest",
    suitableMachineTypes: ["combine-harvester"],
    approximateDuration: "1 day for 4–8 acres (estimate)",
  },
  {
    id: "transport",
    name: "Transport",
    description: "Move harvested produce from field to market or storage.",
    category: "harvest-post-harvest",
    suitableMachineTypes: ["trolley"],
    approximateDuration: "Per trip (estimate)",
  },
];

export const OPERATION_LABELS: Record<FarmOperationId, string> = {
  "seedbed-preparation": "Seedbed preparation",
  sowing: "Sowing",
  spraying: "Spraying",
  harvesting: "Harvesting",
  transport: "Transport",
};

export const MACHINE_TYPE_LABELS: Record<MachineType, string> = {
  tractor: "Tractor",
  rotavator: "Rotavator",
  "seed-drill": "Seed drill",
  sprayer: "Sprayer",
  "combine-harvester": "Combine harvester",
  trolley: "Trolley",
};

/** Provider locations are static dataset labels — not live coordinates. */
export const MACHINERY_PROVIDERS: MachineryProvider[] = [
  {
    id: "mp-01",
    providerName: "AgriServe",
    machineName: "45 HP Tractor + Rotavator",
    machineType: "rotavator",
    operation: "seedbed-preparation",
    location: "Nashik Road",
    distanceKm: 8,
    availabilityStatus: "available",
    estimatedResponse: "~15 minutes",
    suitableFarmSizeAcres: { min: 2, max: 10 },
    source: "demo",
  },
  {
    id: "mp-02",
    providerName: "Kisan Equipment",
    machineName: "50 HP Tractor + Disc Harrow",
    machineType: "tractor",
    operation: "seedbed-preparation",
    location: "Ozar",
    distanceKm: 17,
    availabilityStatus: "busy",
    estimatedResponse: "~30 minutes",
    suitableFarmSizeAcres: { min: 3, max: 12 },
    source: "demo",
  },
  {
    id: "mp-03",
    providerName: "AgriServe",
    machineName: "Tractor-mounted Seed Drill",
    machineType: "seed-drill",
    operation: "sowing",
    location: "Nashik Road",
    distanceKm: 8,
    availabilityStatus: "available",
    estimatedResponse: "~15 minutes",
    suitableFarmSizeAcres: { min: 1, max: 8 },
    source: "demo",
  },
  {
    id: "mp-04",
    providerName: "GreenFields",
    machineName: "Happy Seeder Unit",
    machineType: "seed-drill",
    operation: "sowing",
    location: "Dindori",
    distanceKm: 21,
    availabilityStatus: "unavailable",
    estimatedResponse: "—",
    suitableFarmSizeAcres: { min: 4, max: 15 },
    source: "demo",
  },
  {
    id: "mp-05",
    providerName: "CropCare",
    machineName: "Tractor-mounted Boom Sprayer",
    machineType: "sprayer",
    operation: "spraying",
    location: "Sinnar",
    distanceKm: 12,
    availabilityStatus: "available",
    estimatedResponse: "~20 minutes",
    suitableFarmSizeAcres: { min: 3, max: 12 },
    source: "demo",
  },
  {
    id: "mp-06",
    providerName: "CropCare",
    machineName: "Knapsack Power Sprayer",
    machineType: "sprayer",
    operation: "spraying",
    location: "Panchavati",
    distanceKm: 5,
    availabilityStatus: "busy",
    estimatedResponse: "~25 minutes",
    suitableFarmSizeAcres: { min: 1, max: 5 },
    source: "demo",
  },
  {
    id: "mp-07",
    providerName: "HarvestLink",
    machineName: "Combine Harvester — Medium",
    machineType: "combine-harvester",
    operation: "harvesting",
    location: "Niphad",
    distanceKm: 10,
    availabilityStatus: "available",
    estimatedResponse: "~15 minutes",
    suitableFarmSizeAcres: { min: 2, max: 10 },
    source: "demo",
  },
  {
    id: "mp-08",
    providerName: "FieldMachines",
    machineName: "Combine Harvester — Large",
    machineType: "combine-harvester",
    operation: "harvesting",
    location: "Yeola",
    distanceKm: 26,
    availabilityStatus: "unavailable",
    estimatedResponse: "—",
    suitableFarmSizeAcres: { min: 6, max: 20 },
    source: "demo",
  },
  {
    id: "mp-09",
    providerName: "HarvestLink",
    machineName: "Tractor Trolley — 3 Ton",
    machineType: "trolley",
    operation: "transport",
    location: "Niphad",
    distanceKm: 10,
    availabilityStatus: "available",
    estimatedResponse: "~20 minutes",
    suitableFarmSizeAcres: { min: 1, max: 15 },
    source: "demo",
  },
];
